"""Scientific captions for FastMDXplora report figures."""

from __future__ import annotations


_CAPTIONS: dict[tuple[str, str], str] = {
    ("simulation", "energy_trace"): (
        "Potential, kinetic, and total energy over time provide a quick diagnostic "
        "of simulation stability. Large discontinuities, runaway values, or sudden "
        "jumps may indicate unstable integration settings or problematic system preparation."
    ),
    ("simulation", "simulation_health"): (
        "Temperature, density, and volume traces summarize ensemble health. Stable "
        "temperature and gradually stabilizing density or volume are useful indicators "
        "that equilibration and production settings behaved as expected."
    ),
    ("rmsd", "rmsd"): (
        "RMSD tracks structural deviation from the reference conformation. A plateau "
        "suggests the system reached a relatively stable structural state, while large "
        "drift may indicate ongoing conformational change."
    ),
    ("rmsf", "rmsf"): (
        "RMSF reports residue-level flexibility across the trajectory. Peaks identify "
        "mobile loops, termini, or regions with increased structural fluctuation."
    ),
    ("rg", "rg"): (
        "Radius of gyration tracks global molecular compactness over time. Stable values "
        "suggest the system maintains a consistent overall size, while large shifts may "
        "indicate compaction or expansion."
    ),
    ("hbonds", "hbonds"): (
        "Hydrogen-bond traces summarize polar interaction stability over the trajectory. "
        "Persistent or fluctuating counts can reveal changes in molecular stabilization."
    ),
    ("contacts", "contacts"): (
        "Contact-frequency plots identify residues or molecular groups that remain near "
        "the ligand or interaction partner during the trajectory."
    ),
    ("cluster", "cluster"): (
        "Cluster analysis groups trajectory frames into recurring conformational states, "
        "helping identify dominant structures sampled during simulation."
    ),
    ("dimred", "dimred"): (
        "Dimensionality reduction projects high-dimensional structural motion onto "
        "low-dimensional coordinates, highlighting dominant conformational patterns."
    ),
}


_KEYWORD_CAPTIONS: dict[str, str] = {
    "energy": _CAPTIONS[("simulation", "energy_trace")],
    "health": _CAPTIONS[("simulation", "simulation_health")],
    "temperature": _CAPTIONS[("simulation", "simulation_health")],
    "density": _CAPTIONS[("simulation", "simulation_health")],
    "volume": _CAPTIONS[("simulation", "simulation_health")],
    "rmsd": _CAPTIONS[("rmsd", "rmsd")],
    "rmsf": _CAPTIONS[("rmsf", "rmsf")],
    "rg": _CAPTIONS[("rg", "rg")],
    "hbond": _CAPTIONS[("hbonds", "hbonds")],
    "contact": _CAPTIONS[("contacts", "contacts")],
    "cluster": _CAPTIONS[("cluster", "cluster")],
    "pca": _CAPTIONS[("dimred", "dimred")],
    "dimred": _CAPTIONS[("dimred", "dimred")],
}


def caption_for_figure(section: str, figure_stem: str) -> str:
    """Return a scientific caption for a report figure."""
    section_key = str(section).strip().lower()
    stem_key = str(figure_stem).strip().lower()

    direct = _CAPTIONS.get((section_key, stem_key))
    if direct:
        return direct

    combined = f"{section_key} {stem_key}"
    for keyword, caption in _KEYWORD_CAPTIONS.items():
        if keyword in combined:
            return caption

    pretty_section = section_key.replace("_", " ").title()
    pretty_figure = stem_key.replace("_", " ").title()
    return (
        f"{pretty_figure} summarizes the {pretty_section} result generated by "
        "FastMDXplora. Use this figure together with the recorded analysis "
        "parameters and reproducibility metadata when interpreting the result."
    )
